name: Build and Tag
on:
  push:
    branches:
      - main
concurrency:
  group: sdk-deploy
  cancel-in-progress: true
jobs:
  build-and-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          registry-url: "https://registry.npmjs.org"

      - name: Add .env file
        run: echo "${{ secrets.ENV }}" > .env

      - name: Install dependencies
        run: npm ci

      - name: Run Tests
        run: npm test

      - name: Build
        run: npm run build

      - name: Fetch tags
        run: git fetch --tags

      - name: Parse Tag
        id: parse_tag
        run: |
          LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo '1.0.0')
          IFS='.' read -ra VERSION_PARTS <<< "$LAST_TAG"
          MAJOR=${VERSION_PARTS[0]}
          MINOR=${VERSION_PARTS[1]}
          PATCH=${VERSION_PARTS[2]}
          NEW_TAG="$MAJOR.$MINOR.$((PATCH + 1))"
          while git rev-parse "$NEW_TAG" >/dev/null 2>&1; do
            PATCH=$((PATCH + 1))
            NEW_TAG="$MAJOR.$MINOR.$PATCH"
          done
          echo ::set-output name=tag::${NEW_TAG}

      - name: Update package.json version
        run: |
          npm version --no-git-tag-version $(echo ${{ steps.parse_tag.outputs.tag }})

      - name: Commit changes
        run: |
          git config --local user.email "bot@citizenwallet.xyz"
          git config --local user.name "CW Bot"
          git add package.json
          git commit -m "Add compiled files & tag"
          git push origin main

      - name: Create tag
        run: git tag ${{ steps.parse_tag.outputs.tag }}

      - name: Push Tag
        run: git push origin ${{ steps.parse_tag.outputs.tag }}

      - run: npm ci

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Notify of successful deploy
        run: |
          curl --location '${{ secrets.DISCORD_WEBHOOK_URL }}' \
          --header 'Content-Type: application/json' \
          --data '{
              "content": "new sdk update available: `npm i @citizenwallet/sdk@'${{ steps.parse_tag.outputs.tag }}'`\n or \n `npm i @citizenwallet/sdk@latest` \n\n https://www.npmjs.com/package/@citizenwallet/sdk?activeTab=readme"
          }'
